config/routes.rb
Rails.application.routes.draw do
  resources :reverse_locations
  resources :meet_mes, only: :create

  get '/meetmehalfway' => 'meet_mes#start'
  post '/meetmehalfway' => 'meet_mes#pass'
  get '/meetmehalfway/new' => 'meet_mes#new', as: 'new_meet_me'
  get '/meetmehalfway/:id' => 'meet_mes#show', as: 'meet_me'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :meet_me
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carrier.rb
class Carrier < ApplicationRecord
end

app/models/map.rb
require 'googlestaticmap'

class Map
  def self.map
    map = GoogleStaticMap.new(:zoom => 11, :center => MapLocation.new(:address => "Washington, DC"))
    image_url = map.url(:auto)
  end
end

app/models/meet_me.rb
class MeetMe < ApplicationRecord
  has_many :addresses
  accepts_nested_attributes_for :addresses

  def find_midpoint
    array = self.addresses.map do |address|
      address.name
    end
    Geocoder::Calculations.geographic_center(array)
    #Geocoder takes in multiple addresses and calculates the midpoint in lat long
  end

  def find_address
    midpoint = self.find_midpoint
    ReverseLocation.create(latitude: midpoint[0], longitude: midpoint[1]).address
    #Reverse geocoder takes in the midpoint's coordinates and calculates the actual address
  end

  def find_params
    params = {term: self.term, limit: self.results, sort: 2}
    #returns the attributes of the meet_me object
  end

  def associate_addresses
    self.addresses.each { |address| address.meet_me = self }
    #make address belong to meet_me
  end

  def yelp_query
    address = self.find_address
    params = self.find_params
    begin
      Yelp.client.search(address, params).businesses
    rescue
      self.addresses = []
      #exceptions
    end
  end

  def find_error
    self.yelp_query
    if self.addresses.empty?
      return "you'll probably end up in the ocean"
      #when midpoint doesnt have a valid address
    elsif self.yelp_query.count == 0
      return "There are no vendors of this category in your area."
      #valid midpoint, but no vendors nearby
    elsif self.find_midpoint[0].nan?
      return "Please enter valid addresses."
      #addresses are not in the correct format
    end
  end

  def reset
    error = self.find_error
    self.errors.add(:addresses, error)
    self.addresses = []
    Carrier.last.quantity.times { self.addresses.build }
  end

  def generate_map
    map = GoogleStaticMap.new(:api_key => "AIzaSyCc4G3qvx_jiAqH-pJrPq_o7Dmma2Q14Ic")
    self.addresses.each do |add|
      map.markers << MapMarker.new(:color => "purple", :location => MapLocation.new(:address => add.name))
    end
    map
  end


end

app/models/reverse_location.rb
class ReverseLocation < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meet_mes_controller.rb
require 'googlestaticmap'

class MeetMesController < ApplicationController
  before_action :set_meet_me, only: [:show, :edit, :update, :destroy]

  def start
  end

  def pass
    @carrier = Carrier.create(params.permit(:quantity))
    redirect_to new_meet_me_path
  end

  def new
    @meet_me = MeetMe.new
    amount.times { @meet_me.addresses.build }
  end

  def create
    @meet_me = MeetMe.new(meet_me_params)
    @meet_me.associate_addresses
    if @meet_me.find_error
      @meet_me.reset
      render :new
    else
      @meet_me.save
      redirect_to meet_me_path(@meet_me)
    end
  end

  def show
    @yelp = @meet_me.yelp_query
    @yelp.count == 1 ? @places = "Place" : @places = "Places"
    map = @meet_me.generate_map
    add_yelp_markers_to_map(@yelp, map)
    @img_url = map.url
  end

  private

    def set_meet_me
      @meet_me = MeetMe.find(params[:id])
    end

    def meet_me_params
      params.require(:meet_me).permit(:term, :results, addresses_attributes: [:name])
    end

    def add_yelp_markers_to_map(yelp, map)
      yelp.each do |business|
        add = business.location.display_address.join(" ")
        map.markers << MapMarker.new(:color => "red", :location => MapLocation.new(:address => add))
      end
    end

    def amount
      Carrier.last.quantity
    end

end

app/controllers/reverse_locations_controller.rb
class ReverseLocationsController < ApplicationController
  before_action :set_reverse_location, only: [:show, :edit, :update, :destroy]

  # GET /reverse_locations
  # GET /reverse_locations.json
  def index
    @reverse_locations = ReverseLocation.all
  end

  # GET /reverse_locations/1
  # GET /reverse_locations/1.json
  def show
  end

  # GET /reverse_locations/new
  def new
    @reverse_location = ReverseLocation.new
  end

  # GET /reverse_locations/1/edit
  def edit
  end

  # POST /reverse_locations
  # POST /reverse_locations.json
  def create
    @reverse_location = ReverseLocation.new(reverse_location_params)

    respond_to do |format|
      if @reverse_location.save
        format.html { redirect_to @reverse_location, notice: 'Reverse location was successfully created.' }
        format.json { render :show, status: :created, location: @reverse_location }
      else
        format.html { render :new }
        format.json { render json: @reverse_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reverse_locations/1
  # PATCH/PUT /reverse_locations/1.json
  def update
    respond_to do |format|
      if @reverse_location.update(reverse_location_params)
        format.html { redirect_to @reverse_location, notice: 'Reverse location was successfully updated.' }
        format.json { render :show, status: :ok, location: @reverse_location }
      else
        format.html { render :edit }
        format.json { render json: @reverse_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reverse_locations/1
  # DELETE /reverse_locations/1.json
  def destroy
    @reverse_location.destroy
    respond_to do |format|
      format.html { redirect_to reverse_locations_url, notice: 'Reverse location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reverse_location
      @reverse_location = ReverseLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reverse_location_params
      params.require(:reverse_location).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meet_mes_helper.rb
module MeetMesHelper
end

app/helpers/reverse_locations_helper.rb
module ReverseLocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meet Me Halfway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meet_mes/_form.html.erb
<%= form_for(@meet_me) do |f| %>
  <% if @meet_me.errors.any? %>
    <div id= "error_explanation" >
      <% meet_me.errors.messages.values.each do |message| %>
        <br><%= message.join %></br>
      <% end %>
      </ul>
    </div>
  <% end %>
<p><p>
<div class="mdl-textfield">
  <%= f.label :"enter #{@meet_me.addresses.size.humanize} addresses" %>
    <%= f.fields_for :addresses do |f| %>
      <br>
      <br>
      <%= f.text_field :name, :class => "mdl-textfield__input", :required => true%>
    <% end %>
  </div>
<br>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Category" %>
    <%= f.text_field :term, :class => "mdl-textfield__input"%>
  </div>
<p>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Number of Places" %>
    <%= f.number_field :results, :class => "mdl-textfield__input", :value => "1", :max => "10", :required => true %>
  </div>
<p>
  <div class="actions"><p>
    <%= f.submit 'Find Places' %>
  </div>
<% end %>

app/views/meet_mes/_form.html_BACKUP_4424.erb
<%= form_for(@meet_me) do |f| %>
  <% if @meet_me.errors.any? %>
    <div id= "error_explanation" >
      <% meet_me.errors.messages.values.each do |message| %>
        <br><%= message.join %></br>
      <% end %>
      </ul>
    </div>
  <% end %>
<p><p>
<div class="mdl-textfield">
<<<<<<< HEAD
  <%= f.label :"enter #{@meet_me.addresses.size.humanize} addresses", :class => "mdl-textfield__label" %>
    <%= f.fields_for :addresses do |f| %>
      <br>
      <br>
      <%= f.text_field :name, :class => "mdl-textfield__input", :required => true%>

=======
  <%= f.label :"enter #{@meet_me.addresses.size.humanize} addresses", :class=>"mdl-textfield__label" %>
    <%= f.fields_for :addresses do |f| %>
      <br>
      <br>
      <%= f.text_field :name, :class=>"mdl-textfield__input", :required => true%>
      
>>>>>>> 1e2ab4cb5ead6e867c88ade0bf579ea490c20a0d
    <% end %>
  </div>
<br>
  <div class="mdl-textfield mdl-js-textfield">
<<<<<<< HEAD
    <%= f.label :"Category", :class => "mdl-textfield__label" %>
    <%= f.text_field :term, :class => "mdl-textfield__input", :required => true%>
  </div>
<p>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Number of Places", :class => "mdl-textfield__label" %>
    <%= f.number_field :results, :class => "mdl-textfield__input", :value => "1", :max => "10", :required => true %>
=======
    <%= f.label :"Category", :class=>"mdl-textfield__label" %>
    <%= f.text_field :term, :class=>"mdl-textfield__input", :required => true%>
  </div>
<p>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Number of Places", :class=>"mdl-textfield__label" %>
    <%= f.number_field :results, :class=>"mdl-textfield__input", :max=>"10",:required => true %>
>>>>>>> 1e2ab4cb5ead6e867c88ade0bf579ea490c20a0d
  </div>
<p>
  <div class="actions"><p>
    <%= f.submit 'Find Places' %>
  </div>
  </h6>
<% end %>

app/views/meet_mes/_form.html_BASE_4424.erb
<%= form_for(@meet_me) do |f| %>
  <% if @meet_me.errors.any? %>
    <div id="error_explanation">
      <% meet_me.errors.messages.values.each do |message| %>
        <br><%= message.join %></br>
      <% end %>
      </ul>
    </div>
  <% end %>
<p><p><h6>
  <%= "enter #{@meet_me.addresses.size.humanize} addresses:" %><br>
    <%= f.fields_for :addresses do |addresses_form| %>
      <br>
        <%= addresses_form.text_field :name %>
      </br>
    <% end %>
<p>
  <div class="field">
    <%= "category" %>
    <%= f.text_field :term, :required => true %>
  </div>
<p>
  <div class="field">
    <%= "number of results" %>
    <%= f.number_field :results, :value => 1, :min => 1, :required => true %>
  </div>
<p>
  <div class="actions"><p>
    <%= f.submit 'Find Places' %>
  </div></h6>
<% end %>

app/views/meet_mes/_form.html_LOCAL_4424.erb
<%= form_for(@meet_me) do |f| %>
  <% if @meet_me.errors.any? %>
    <div id= "error_explanation" >
      <% meet_me.errors.messages.values.each do |message| %>
        <br><%= message.join %></br>
      <% end %>
      </ul>
    </div>
  <% end %>
<p><p>
<div class="mdl-textfield">
  <%= f.label :"enter #{@meet_me.addresses.size.humanize} addresses", :class => "mdl-textfield__label" %>
    <%= f.fields_for :addresses do |f| %>
      <br>
      <br>
      <%= f.text_field :name, :class => "mdl-textfield__input", :required => true%>

    <% end %>
  </div>
<br>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Category", :class => "mdl-textfield__label" %>
    <%= f.text_field :term, :class => "mdl-textfield__input", :required => true%>
  </div>
<p>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Number of Places", :class => "mdl-textfield__label" %>
    <%= f.number_field :results, :class => "mdl-textfield__input", :value => "1", :max => "10", :required => true %>
  </div>
<p>
  <div class="actions"><p>
    <%= f.submit 'Find Places' %>
  </div>
  </h6>
<% end %>

app/views/meet_mes/_form.html_REMOTE_4424.erb
<%= form_for(@meet_me) do |f| %>
  <% if @meet_me.errors.any? %>
    <div id="error_explanation">
      <% meet_me.errors.messages.values.each do |message| %>
        <br><%= message.join %></br>
      <% end %>
      </ul>
    </div>
  <% end %>
<p><p>
<div class="mdl-textfield">
  <%= f.label :"enter #{@meet_me.addresses.size.humanize} addresses", :class=>"mdl-textfield__label" %>
    <%= f.fields_for :addresses do |f| %>
      <br>
      <br>
      <%= f.text_field :name, :class=>"mdl-textfield__input", :required => true%>
      
    <% end %>
  </div>
<br>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Category", :class=>"mdl-textfield__label" %>
    <%= f.text_field :term, :class=>"mdl-textfield__input", :required => true%>
  </div>
<p>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :"Number of Places", :class=>"mdl-textfield__label" %>
    <%= f.number_field :results, :class=>"mdl-textfield__input", :max=>"10",:required => true %>
  </div>
<p>
  <div class="actions"><p>
    <%= f.submit 'Find Places' %>
  </div>
  </h6>
<% end %>

app/views/meet_mes/new.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

<body>
 <font size='15'>MEET ME HALFWAY</font>
<p>
<%= render 'form', meet_me: @meet_me %>
</body>

app/views/meet_mes/show.html.erb
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-yellow.min.css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

<center>
<font size="6"><%= "#{@yelp.count.humanize.capitalize} #{@places} for #{@meet_me.term.split.map { |word| word.capitalize }.join(" ")}" %></font><p>
<p>between
  <% @meet_me.addresses.each do |address| %>
  <p><%= address.name %>
  <% end %>
</p>
<p>. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .</p>
<p><img src = <%=@img_url%>></p>
<p>. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .</p>

<div style="width:50%; word-wrap:break-word;center" >
<% @yelp.each do |business|%><p>
<font size="5"><%= link_to business.name, business.url%></font>
<p><%= business.location.display_address.join(" ") %>
<p><%= business.display_phone%>
<p><%= "#{business.rating} stars with #{business.review_count} reviews" %>
<p><%= "\"#{business.snippet_text}\"" %>
<br>
<% end %>
</div>
<p>. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .</p>

<p><%= link_to 'back', meetmehalfway_path %></p>
</center>

app/views/meet_mes/start.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

<%= form_tag("/meetmehalfway", method: "post") do %>
  <%= label_tag(:people, "How many people?") %>
  <%= number_field_tag 'quantity', 2, in: 1...10 %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/reverse_locations/_form.html.erb
<%= form_for(reverse_location) do |f| %>
  <% if reverse_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reverse_location.errors.count, "error") %> prohibited this reverse_location from being saved:</h2>

      <ul>
      <% reverse_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reverse_locations/edit.html.erb
<h1>Editing Reverse Location</h1>

<%= render 'form', reverse_location: @reverse_location %>

<%= link_to 'Show', @reverse_location %> |
<%= link_to 'Back', reverse_locations_path %>

app/views/reverse_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reverse Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reverse_locations.each do |reverse_location| %>
      <tr>
        <td><%= reverse_location.address %></td>
        <td><%= reverse_location.latitude %></td>
        <td><%= reverse_location.longitude %></td>
        <td><%= link_to 'Show', reverse_location %></td>
        <td><%= link_to 'Edit', edit_reverse_location_path(reverse_location) %></td>
        <td><%= link_to 'Destroy', reverse_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reverse Location', new_reverse_location_path %>

app/views/reverse_locations/new.html.erb
<h1>New Reverse Location</h1>

<%= render 'form', reverse_location: @reverse_location %>

<%= link_to 'Back', reverse_locations_path %>

app/views/reverse_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @reverse_location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @reverse_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @reverse_location.longitude %>
</p>

<%= link_to 'Edit', edit_reverse_location_path(@reverse_location) %> |
<%= link_to 'Back', reverse_locations_path %>